[workspace]
members = ["src/core", "src/cli"]
resolver = "3"

[workspace.package]
version = "0.1.0" # x-release-please-version
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/twangodev/postframe"

[workspace.dependencies]
postframe-core = { path = "src/core" }

anyhow = "1"
clap = { version = "4", features = ["derive"] }
